"""Initial tables

Revision ID: 9a4b80142bda
Revises: 
Create Date: 2025-04-22 17:42:39.105653

Creates ALL 42 tables, indexes, foreign keys, and check constraints
that match the current SQLAlchemy models.

Production safety:
- Idempotent: detects existing tables and skips if already present.
- No DROP TABLE / DROP COLUMN in upgrade().
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4b80142bda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- Idempotency guard ------------------------------------------------
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if inspector.has_table("users"):
        print(
            "INFO [initial_tables] Tables already exist — skipping "
            "creation. This is expected for databases bootstrapped by "
            "create_all(). Migration marked as applied."
        )
        return
    # ----------------------------------------------------------------------
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_perks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('effect', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('craft_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schedule_cron', sa.String(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('rewards', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('equipment', 'artifact', 'resource', 'material', 'consumable', 'weapon', 'armor', 'helmet', name='itemtype'), nullable=False),
    sa.Column('bonus_strength', sa.Integer(), nullable=True),
    sa.Column('bonus_agility', sa.Integer(), nullable=True),
    sa.Column('bonus_intelligence', sa.Integer(), nullable=True),
    sa.Column('bonus_endurance', sa.Integer(), nullable=True),
    sa.Column('bonus_speed', sa.Integer(), nullable=True),
    sa.Column('bonus_health', sa.Integer(), nullable=True),
    sa.Column('bonus_defense', sa.Integer(), nullable=True),
    sa.Column('bonus_luck', sa.Integer(), nullable=True),
    sa.Column('slot_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_id'), ['id'], unique=False)

    op.create_table('mob_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('base_stats', sa.JSON(), nullable=False),
    sa.Column('is_boss', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('effect_type', sa.String(length=30), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=True),
    sa.Column('modifiers', sa.JSON(), nullable=True),
    sa.Column('affected', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('quantum_heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('quantum_crafting_skill', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quantum_heroes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_heroes_id'), ['id'], unique=False)

    op.create_table('quantum_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('output_slot', sa.String(), nullable=False),
    sa.Column('required_resources', sa.JSON(), nullable=False),
    sa.Column('mutation_chance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quantum_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_recipes_id'), ['id'], unique=False)

    op.create_table('quantum_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint("name IN ('Quantum Dust','Cosmic Alloy','Photon Shard','Nano Gel')", name='ck_resource_name'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quantum_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_resources_id'), ['id'], unique=False)

    op.create_table('raid_bosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gen_min', sa.Integer(), nullable=False),
    sa.Column('gen_max', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('PvE', 'PvP', name='resourcetype'), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournament_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('min_rank', sa.Integer(), nullable=True),
    sa.Column('max_rank', sa.Integer(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_google_account', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_user_balance_non_negative'),
    sa.CheckConstraint('reserved >= 0', name='ck_user_reserved_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_id'), ['id'], unique=False)

    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('start_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', 'CANCELLED', 'EXPIRED', name='auctionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('current_price > 0', name='ck_auction_current_price_positive'),
    sa.CheckConstraint('start_price > 0', name='ck_auction_start_price_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auctions_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_auctions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auctions_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auctions_status'), ['status'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)

    op.create_table('craft_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('boss_id', sa.Integer(), nullable=True),
    sa.Column('drop_chance', sa.Float(), nullable=True),
    sa.Column('craft_time_sec', sa.Integer(), nullable=True),
    sa.Column('result_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['raid_bosses.id'], ),
    sa.ForeignKeyConstraint(['result_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currency_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currency_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_currency_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('event_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['event_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('endurance', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('luck', sa.Integer(), nullable=False),
    sa.Column('field_of_view', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('is_training', sa.Boolean(), nullable=True),
    sa.Column('training_end_time', sa.DateTime(), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_dead', sa.Boolean(), nullable=True),
    sa.Column('dead_until', sa.DateTime(), nullable=True),
    sa.Column('is_on_auction', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('gold >= 0', name='ck_hero_gold_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heroes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_heroes_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_heroes_owner_deleted', ['owner_id', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_heroes_owner_id'), ['owner_id'], unique=False)

    op.create_table('leaderboard',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('mob_perks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mob_template_id', sa.Integer(), nullable=False),
    sa.Column('perk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mob_template_id'], ['mob_templates.id'], ),
    sa.ForeignKeyConstraint(['perk_id'], ['boss_perks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offline_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offline_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offline_messages_id'), ['id'], unique=False)

    op.create_table('pvp_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantum_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('stability', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=False),
    sa.Column('mutation_chance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['quantum_heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quantum_equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_equipment_id'), ['id'], unique=False)

    op.create_table('raid_arena_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_ids', sa.JSON(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('waves', sa.JSON(), nullable=True),
    sa.Column('current_wave', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['raid_bosses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raid_drops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('chance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['raid_bosses.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='_user_item_uc')
    )
    with op.batch_alter_table('stash', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stash_id'), ['id'], unique=False)

    op.create_table('tournament_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('bracket', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['tournament_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('starting_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('buyout_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', 'CANCELLED', 'EXPIRED', name='auctionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('buyout_price IS NULL OR buyout_price > 0', name='ck_lot_buyout_price_positive'),
    sa.CheckConstraint('current_price > 0', name='ck_lot_current_price_positive'),
    sa.CheckConstraint('starting_price > 0', name='ck_lot_starting_price_positive'),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero_id')
    )
    with op.batch_alter_table('auction_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auction_lots_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_lots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_lots_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_lots_status'), ['status'], unique=False)

    op.create_table('battle_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bettor_id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_battle_bet_amount_positive'),
    sa.ForeignKeyConstraint(['bettor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bettor_id', 'hero_id', name='uq_battle_bet_bettor_hero')
    )
    with op.batch_alter_table('battle_bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battle_bets_bettor_id'), ['bettor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_battle_bets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_battle_bets_hero_id'), ['hero_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_battle_bets_id'), ['id'], unique=False)

    op.create_table('battle_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battle_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battle_queue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_battle_queue_hero_id'), ['hero_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_battle_queue_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_battle_queue_player_id'), ['player_id'], unique=True)

    op.create_table('craft_recipe_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['craft_recipes.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crafted_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result_item_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('is_mutated', sa.Boolean(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['craft_recipes.id'], ),
    sa.ForeignKeyConstraint(['result_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero_id', 'slot', name='_hero_slot_uc')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_id'), ['id'], unique=False)

    op.create_table('hero_perks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('perk_id', sa.Integer(), nullable=True),
    sa.Column('perk_name', sa.String(), nullable=True),
    sa.Column('perk_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perk_id'], ['perks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero_id', 'perk_id', name='_hero_perk_uc')
    )
    op.create_table('pve_battle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['raid_arena_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvp_battle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['pvp_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantum_crafted_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['quantum_equipment.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['quantum_heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quantum_crafted_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_crafted_items_id'), ['id'], unique=False)

    op.create_table('recipe_drops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('chance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['raid_bosses.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['craft_recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('max_amount > 0', name='ck_autobid_max_amount_positive'),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auto_bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auto_bids_id'), ['id'], unique=False)

    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_bid_amount_positive'),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_bidder_id'), ['bidder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_request_id'), ['request_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
